[package]
name = "light_sup"
version = "0.1.0"
authors = ["Anton Kaliaev <anton.kalyaev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
